version: 2

terraform: &terraform
  docker:
    - image: hashicorp/terraform:0.9.8
  working_directory: ~/repo

jobs:
  validate:
    <<: *terraform
    steps:
      - checkout
      
      - run:
          name: terraform init
          command: terraform init -input=false
      
      - run:
          name: Install tflint
          command: curl -L -o /tmp/tflint.zip https://github.com/wata727/tflint/releases/download/v0.4.2/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin
      
      - run: make test          
      
      - persist_to_workspace:
          root: .
          paths: .

      - store_artifacts:
          path: reports
          destination: reports

workflows:
  version: 2
  build:
    jobs:
      - validate
